version: '3.8'
services:
  db:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    entrypoint: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=3306
      - DJANGO_DB_NAME=mydatabase
      - DJANGO_DB_USER=myuser
      - DJANGO_DB_PASSWORD=mypassword
volumes:
  mysql_data:
